{% set name = "pysubgroup" %}
{% set version = "0.7.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pysubgroup-{{ version }}.tar.gz
  sha256: 740a30576d85bc151bd57442ccffb47ef22b71e29f72a12370afc5b9fce72e8d

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=46.1.0
    - setuptools-scm >=5
    - pip
  run:
    - python >={{ python_min }}
    - importlib-metadata
    - pandas >=0.24.0
    - scipy
    - numpy
    - matplotlib-base

test:
  imports:
    - pysubgroup
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/flemmerich/pysubgroup
  summary: pysubgroup is a Python library for the data analysis task of subgroup discovery.
  dev_url: https://github.com/flemmerich/pysubgroup
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - mgbckr
    - flemmerich
    - Feelx234
